name: LANDING_ZONE_SETUP

on:
  push:
    branches:
    - main
    - features/**
  pull_request:
  workflow_dispatch:

jobs:
  First_JOB:
    name: BUILD_STAGE_1
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
  
    steps:
    - name: Azure Login
      uses: azure/login@v2.3.0
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Checkout Code
      uses: actions/checkout@v3

    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v2.0.3

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan

      
      
